# Generated by Django 6.0.4 on 2026-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('alert_threshold', models.IntegerField(default=80)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('near_limit', 'Near Limit'), ('exceeded', 'Exceeded')], default='on_track', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
